#!/bin/sh

dash_ver=0.5.12

usage () {
cat <<'EOT'
This script is derived from the wasix test code builder.
It can be called in 3 ways.

1. Clean and build AWK with the supplied makefile,
   then rename the resulting a.out to awk.wasm.
     ./wasixbuild

2. Issue explicit build commands, essentially executing
   CC CFLAGS LDFLAGS $@
     ./wasixbuild -c b.c

3. Issue explicit make commands
   ./wasixbuild make -f makefile cleaner
EOT
}

if [ "$1" = -h ] || [ "$1" = --help ] || [ "$1" = help ]; then
  usage
  exit
fi

if [ -z "${WASI_SDK}" ]; then
  echo "WASI_SDK is not found"
  exit 1
fi

if [ -z "${WASIX_SYSROOT}" ]; then
  echo "WASIX_SYSROOT is not found"
  exit 1
fi

if ! command -v cc; then
  echo "A native cc command is required for building utilities"
  exit 1
fi

export RANLIB="$WASI_SDK/bin/ranlib"
export AR="$WASI_SDK/bin/ar"
export NM="$WASI_SDK/bin/nm"
export CC="$WASI_SDK/bin/clang"
export CXX="$WASI_SDK/bin/clang"
export CFLAGS="\
--sysroot=$WASIX_SYSROOT \
-matomics \
-mbulk-memory \
-mmutable-globals \
-pthread \
-mthread-model posix \
-ftls-model=local-exec \
-fno-trapping-math \
-D_WASI_EMULATED_MMAN \
-D_WASI_EMULATED_SIGNAL \
-D_WASI_EMULATED_PROCESS_CLOCKS \
-O2 \
-g \
-flto"
export CFLAGSS="$CFLAGS"
#export LD="$WASI_SDK/bin/wasm-ld"
export LD="$CC"
export LDFLAGS="\
-Wl,--shared-memory \
-Wl,--max-memory=4294967296 \
-Wl,--import-memory \
-Wl,--export-dynamic \
-Wl,--export=__heap_base \
-Wl,--export=__stack_pointer \
-Wl,--export=__data_end \
-Wl,--export=__wasm_init_tls \
-Wl,--export=__tls_size \
-Wl,--export=__tls_align \
-Wl,--export=__tls_base \
-Wl,--export=__wasm_signal \
-lwasi-emulated-mman \
-O3 \
-g \
-flto"

if [ ! -f "dash-$dash_ver.tar.gz" ]; then
  if ! curl -OL "https://git.kernel.org/pub/scm/utils/dash/dash.git/snapshot/dash-$dash_ver.tar.gz"; then
    echo "Could not download dash. CURL failed with exit code $?"
    echo "https://git.kernel.org/pub/scm/utils/dash/dash.git/snapshot/dash-$dash_ver.tar.gz"
    exit 1
  fi
fi

if [ ! -d "dash-$dash_ver.tar.gz" ]; then
  if ! tar xf dash-$dash_ver.tar.gz; then
    echo "tar failed to extract dash-$dash_ver.tar.gz with exit code $?"
    exit 1
  fi
fi

cd dash-$dash_ver
./autogen.sh
./configure --host wasm32-unknown-wasi
make

if [ -f src/dash ]; then
  cp src/dash ../
  cd ..
  wasm-opt -O4 --asyncify -g dash -o dash.wasm
fi

